# Generated by Django 4.2.5 on 2024-01-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0027_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="matrix_id",
            field=models.CharField(default=""),
        ),
    ]
