# Generated by Django 4.2.5 on 2024-01-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0028_user_matrix_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matrix_id",
            field=models.CharField(default="", max_length=120),
        ),
    ]
