# Generated by Django 5.1.3 on 2024-11-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0029_alter_user_avatar_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="matrix_id",
            field=models.CharField(default="", max_length=120),
        ),
    ]
