# Generated by Django 4.2.5 on 2024-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0074_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="on_website",
            field=models.BooleanField(default=True),
        ),
    ]
