# Generated by Django 5.1.3 on 2024-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0077_answeroption_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="on_website",
            field=models.BooleanField(default=True),
        ),
    ]
