# Generated by Django 5.1.3 on 2024-11-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0011_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="cc",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
