# Generated by Django 4.2.5 on 2023-12-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0011_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="cc",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
